factory-reset: Switch to the stable branch when factory reseting
We always want a factory reset to land on the stable branch, so ensure we
switch to it before checking for and installing an update. If we are
already on the stable branch this is harmless.

diff --git a/factory-reset b/factory-reset
--- a/factory-reset
+++ b/factory-reset
@@ -114,6 +114,14 @@ update_os ()
         return 0
     fi
 
+    # Ensure we are on the stable branch, we always want to do a factory reset
+    # to this. If we are already on this branch, this isn't going to hurt.
+    if ! atomupd-manager switch-branch stable
+    then
+        log_msg "Failed to switch to the stable branch"
+        return 1
+    fi
+
     atomupd-manager custom-update --verbose stable | while IFS= read -r line; do
         if [[ "$line" =~ ^[0-9]+\.[0-9]+% ]]; then
             log_msg "New OS image: $line"
